.TH "square-root Directory Reference" 3 "Thu Sep 24 2020" "square-root" \" -*- nroff -*-
.ad l
.nh
.SH NAME
square-root Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfunctions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfunctions\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
