.TH "square-root/main.cpp" 3 "Thu Sep 24 2020" "square-root" \" -*- nroff -*-
.ad l
.nh
.SH NAME
square-root/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'functions\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, const char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, const char * argv[])"

.PP
Definition at line 11 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for square-root from the source code\&.
