osx_image: xcode10.2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.3.1.app
      - name: Build
        run: xcodebuild -configuration Debug

